### ISSUE TITLE
Source code for Atom Table Monitor (GUI)?

### ISSUE THREAD

**Issue by raelb** [JordiCorbilla/atom-table-monitor#3]
Hi,

I seem to be missing something. You have lots of pictures of "Atom Table Monitor v1.2", yet the repository only includes source for a service with no GUI at all.

Is this GUI not open source? or is it at another location?

Thanks

**Comment by JordiCorbilla** [comment]
Hi there,

Sorry but that code is not open source yet. I might put it some day.

Cheers,
Jordi
