### ISSUE TITLE
Not a real Issue but...

### ISSUE THREAD

**Issue by Bit-Fiddler** [JordiCorbilla/atom-table-monitor#4]
I am trying to write some code in VB dealing with atom tables.  I was wondering if I could get with you for some help on my project?

basically I was wondering if you know how to get VB6 to enumerate the atom table and store all the atom index/contents in an array.  This sounds very similar to what you are doing here, so I assume it will somehow be possible with an API call?

**Comment by JordiCorbilla** [comment]
Hi There, if you read my readme you'll see what's the method I use to list the atoms. Hope this helps!
