### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Memnarch** [JordiCorbilla/atom-table-monitor#5]
Justw anted to thank you. 1 or 2 years ago, this helped me to verify a RWM-Leak. Ironically it was one in the VCL of xe(they fixed it in XE2 or 3 iirc)

**Comment by JordiCorbilla** [comment]
thanks @Memnarch! Indeed they fixed it but this was really a high issue at the time! I'm glad you found it useful!

**Comment by Memnarch** [comment]
I had to hook RegisterWindowMessage in our Application to fix it back then :D
We actually have a usecase were this little leak killed customers sessions oO
