### ISSUE TITLE
Counters unmatched graph

### ISSUE THREAD

**Issue by lbcsy** [JordiCorbilla/atom-table-monitor#6]
Hi Jordi,

I have been using your great tool to prove that I have fixed one of my Delphi application of RWM leaking.

However, I have noticed a different between the Counters tab and the graph:
![image](https://user-images.githubusercontent.com/5274272/35077925-af9cbdee-fc53-11e7-83c7-a37583965cc5.png)
On the above screenshot, you can see the number of Total Atoms (RWM Atom Table) seems different and bigger that the one is showing on the graph.

Also, as Delphi only leaks atom in RWM, thus I only interested in Delphi's atom in RWM, it will be more useful if the counters can show numbers in global and RWM instead of just a total number in these two.

Thanks,
Bo

**Comment by JordiCorbilla** [comment]
Hi Bo,

Let me have a look. Something might be off.

Cheers,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Bo,

Please check out the latest release (v1.5) which fixes the syncing of the counters.
![image](https://user-images.githubusercontent.com/7347994/35165861-c2630c7c-fd47-11e7-9f20-05a7bfeaa8e3.png)

Cheers,
Jordi
