### ISSUE TITLE
Counters in Global Atom Table and RWM Atom Table

### ISSUE THREAD

**Issue by lbcsy** [JordiCorbilla/atom-table-monitor#7]
As a Delphi programmer, I am more interested in Counter for pattern "ControlOfs[0-9A-Z!?/*+-]+" which I can use it to test if my application is leaking in RWM Atom Table. A Delphi application use this same pattern to create at lease one entry in global table and one in RWM table, but the counter does not distinguish the number in these two area, makes the testing a little bit harder when all its goal is to make sure number of "ControlOfs[0-9A-Z!?/*+-]+" in RWM is not growing.

**Comment by JordiCorbilla** [comment]
Hi, The tool show the total of atoms that are present in the atom table (being global or RWM). If you use the latest version, you'll see that the counters tab gets updated automatically and that the counts value increases there over time. I might do a specific chart for it if I have the time.

![image](https://user-images.githubusercontent.com/7347994/35356559-b1e1dd06-0148-11e8-857c-58144ff64539.png)

**Comment by JordiCorbilla** [comment]
Please have a look at version 1.6 as it should have what you asked. In the end I had to spend some time on it as there were some other request very similar to yours.

Cheers,
Jordi
