### ISSUE TITLE
Different value of counters in 1.5 and 1.6

### ISSUE THREAD

**Issue by lbcsy** [JordiCorbilla/atom-table-monitor#8]
Hi Jordi,

It is interesting that the values of counters in 1.5 and 1.6 might be different when they are both running.
I have two screen shots, the second one was captured after I restarted 1.5.
![2018-01-25 10_23_25-_new 2 - notepad](https://user-images.githubusercontent.com/5274272/35362821-0dd3582a-01bb-11e8-867a-ea4e2d203e5d.png)
![2018-01-25 10_27_23-_new 2 - notepad](https://user-images.githubusercontent.com/5274272/35362826-11884bce-01bb-11e8-93f0-3baceb845506.png)

**Comment by JordiCorbilla** [comment]
Hi,

Let me have a look, might be something off somewhere but it should work in the same way.

Cheers,
Jordi

**Comment by JordiCorbilla** [comment]
Just tried with both versions and I'm getting the same counters. The code hasn't changed there, it still uses the same regular expressions and the same counters.

![image](https://user-images.githubusercontent.com/7347994/35413416-3e542108-0217-11e8-8315-a39bdf0e5626.png)
